/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taskmanager;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author JiaLenovo
 */
public class TaskAdder extends javax.swing.JFrame {

    /**
     * Creates new form TaskAdder
     */
    String list;
    String deleteList;
    boolean tableAdded = false;

    public String getList() {
        return list;
    }
    public String getDeleteList(){
        return deleteList;
    }
    public boolean getTableAdded(){
        return tableAdded;
    }

    public TaskAdder() {
        initComponents();
        list = "";
        deleteList = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTaskLists = new javax.swing.JPanel();
        pnlListButtons = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tableSelector = new javax.swing.JComboBox<>();
        btnAddEditList = new javax.swing.JButton();
        btnDeleteList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTableNames = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        AddTable = new javax.swing.JButton();
        txtSelectedList = new javax.swing.JTextField();
        ((AbstractDocument)txtSelectedList.getDocument()).setDocumentFilter(new TaskAddFilter(Pattern.compile("[\\s]")));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Your Lists | Task Manager");
        setPreferredSize(new java.awt.Dimension(566, 370));
        getContentPane().setLayout(new java.awt.FlowLayout());

        pnlTaskLists.setAutoscrolls(true);
        pnlTaskLists.setMinimumSize(new java.awt.Dimension(546, 296));
        pnlTaskLists.setPreferredSize(new java.awt.Dimension(546, 350));

        pnlListButtons.setPreferredSize(new java.awt.Dimension(315, 10));

        jLabel2.setText("Select Table");

        tableSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tableSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableSelectorActionPerformed(evt);
            }
        });

        btnAddEditList.setText("Select List");
        btnAddEditList.setToolTipText("Add or Edit the List");
        btnAddEditList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEditListActionPerformed(evt);
            }
        });

        btnDeleteList.setText("Delete List");
        btnDeleteList.setToolTipText("Delete the list! Warning! No undo!");
        btnDeleteList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListButtonsLayout = new javax.swing.GroupLayout(pnlListButtons);
        pnlListButtons.setLayout(pnlListButtonsLayout);
        pnlListButtonsLayout.setHorizontalGroup(
            pnlListButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnAddEditList)
                .addGap(5, 5, 5)
                .addComponent(btnDeleteList)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        pnlListButtonsLayout.setVerticalGroup(
            pnlListButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListButtonsLayout.createSequentialGroup()
                .addGroup(pnlListButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListButtonsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlListButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tableSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(pnlListButtonsLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnAddEditList))
                    .addGroup(pnlListButtonsLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnDeleteList)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTableNames.setEditable(false);
        txtTableNames.setColumns(20);
        txtTableNames.setLineWrap(true);
        txtTableNames.setRows(5);
        txtTableNames.setToolTipText("The master list of all of your task lists.");
        txtTableNames.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtTableNames);

        jLabel1.setText("Enter New Table Name");
        jLabel1.setToolTipText("");
        jLabel1.setPreferredSize(new java.awt.Dimension(85, 20));

        AddTable.setText("Add");
        AddTable.setToolTipText("Add or Edit the List");
        AddTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTableActionPerformed(evt);
            }
        });

        txtSelectedList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelectedListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTaskListsLayout = new javax.swing.GroupLayout(pnlTaskLists);
        pnlTaskLists.setLayout(pnlTaskListsLayout);
        pnlTaskListsLayout.setHorizontalGroup(
            pnlTaskListsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaskListsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSelectedList, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddTable)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlTaskListsLayout.createSequentialGroup()
                .addGroup(pnlTaskListsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlListButtons, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                .addContainerGap(3, Short.MAX_VALUE))
        );
        pnlTaskListsLayout.setVerticalGroup(
            pnlTaskListsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaskListsLayout.createSequentialGroup()
                .addGroup(pnlTaskListsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTaskListsLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlTaskListsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddTable)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTaskListsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSelectedList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTaskLists);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEditListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEditListActionPerformed
        if(txtSelectedList.getText().isEmpty() == false){
            list = txtSelectedList.getText();
            deleteList = "";
            this.dispose();
        }
        else if(tableSelector.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "Nothing to select");
        }
        else{
            list = tableSelector.getSelectedItem().toString();
            deleteList = "";
            this.dispose();
        }
        
    }//GEN-LAST:event_btnAddEditListActionPerformed

    private void btnDeleteListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteListActionPerformed
        if(txtSelectedList.getText().isEmpty() == false){
            deleteList = txtSelectedList.getText();
            list = "";
            this.dispose();
        }
        else if(tableSelector.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "Nothing to delete");
        }
        else{
            deleteList = tableSelector.getSelectedItem().toString();
            list = "";
            this.dispose();
        }
            
    }//GEN-LAST:event_btnDeleteListActionPerformed

    private void tableSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableSelectorActionPerformed

    private void AddTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTableActionPerformed
        if(txtSelectedList.getText().isEmpty() == false){
            list = txtSelectedList.getText();
            tableAdded = true;
            deleteList = "";
        this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please enter a name for your task list");
        }
        
    }//GEN-LAST:event_AddTableActionPerformed

    private void txtSelectedListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectedListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelectedListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskAdder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TaskAdder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTable;
    private javax.swing.JButton btnAddEditList;
    private javax.swing.JButton btnDeleteList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlListButtons;
    private javax.swing.JPanel pnlTaskLists;
    public javax.swing.JComboBox<String> tableSelector;
    private javax.swing.JTextField txtSelectedList;
    public javax.swing.JTextArea txtTableNames;
    // End of variables declaration//GEN-END:variables
}